snippets/urls.py
from django.urls import path, include
from snippets import views
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import url

app_name = 'snippets'

urlpatterns = [
    # path('snippets/', views.snippet_list),
    # path('snippets/', views.SnippetList.as_view(), name='snippet-list'),
    # # # path('snippets/<int:pk>/', views.snippet_detail),
    # path('snippets/<int:pk>/', views.SnippetDetail.as_view(), name='snippet-detail'),
    # path('users/', views.UserList.as_view(), name='user-list'),
    # path('users/<int:pk>/', views.UserDetail.as_view(), name='user-detail'),

    path('create_book_normal/', views.create_book_normal, name='create_book_normal'),
    path('book_list/', views.BookList.as_view(), name='book_list'),
    path('add_bird/', views.BirdAddView.as_view(), name="add_bird"),
    path('bird_list/', views.BirdListView.as_view(), name="bird_list"),

    path('person_list/', views.PersonListView.as_view(), name='person_changelist'),
    path('person_add/', views.PersonCreateView.as_view(), name='person_add'),
    path('person_change/<int:pk>/', views.PersonUpdateView.as_view(), name='person_change'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('ajax/load-models/', views.load_model_type, name='ajax_load_models'),
]

urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),
    path('', views.api_root),
    path('snippets/<int:pk>/highlight', views.SnippetHighlight.as_view(), name='snippet-highlight'),
]

urlpatterns += [
    # url(r'^book/create', views.ComicsCreate, name="BookCreate"),
    # url(r'^author/create', views.AuthorCreatePopup, name="AuthorCreate"),
    # url(r'^author/(?P<pk>\d+)/edit', views.AuthorEditPopup, name="AuthorEdit"),
    # url(r'^author/ajax/get_author_id', views.get_author_id, name="get_author_id"),
    path('comics/create/', views.ComicsCreate, name="ComicsCreate"),
    path('author/create/', views.AuthorCreatePopup, name="AuthorCreate"),
    path('author/<int:pk>/edit/', views.AuthorEditPopup, name="AuthorEdit"),
    path('author/ajax/get_author_id/', views.get_author_id, name="get_author_id"),
]
# urlpatterns = format_suffix_patterns(urlpatterns)

tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('snippets/', include('snippets.urls', namespace='snippets')),
    path('drawcircuit/', include('drawcircuit.urls', namespace='drawcircuit')),

]

snippets/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles

from pygments.lexers import get_lexer_by_name
from pygments.formatters.html import HtmlFormatter
from pygments import highlight

LEXERS = [item for item in get_all_lexers() if item[1]]
LANGUAGE_CHOICE = sorted([(item[1][0], item[0]) for item in LEXERS])
STYLE_CHOICES = sorted([(item, item) for item in get_all_styles()])


class Snippet(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100, blank=True, default='')
    code = models.TextField()
    linenos = models.BooleanField(default=False)
    language = models.CharField(choices=LANGUAGE_CHOICE, default='python', max_length=100)
    style = models.CharField(choices=STYLE_CHOICES, default='friendly', max_length=100)
    owner = models.ForeignKey('auth.User', related_name='snippets', on_delete=models.CASCADE)
    highlighted = models.TextField()

    class Meta:
        ordering = ['created']

    def save(self, *args, **kwargs):
        # use pygments lib to create highlighted HTML, representation of the code snippet
        lexer = get_lexer_by_name(self.language)
        linenos = 'table' if self.linenos else None
        options = {'title': self.title} if self.title else {}
        formatter = HtmlFormatter(style=self.style, linenos=linenos, full=True, **options)
        self.highlighted = highlight(self.code, lexer, formatter)
        super(Snippet, self).save(*args, **kwargs)


class Book(models.Model):
    name = models.CharField(max_length=255)
    isbn_number = models.CharField(max_length=13)

    class Meta:
        db_table = 'book'

    def __str__(self):
        return self.name


class Bird(models.Model):
    common_name = models.CharField(max_length=250)
    scientific_name = models.CharField(max_length=250)

    def __str__(self):
        return self.common_name


# Add/Edit button on Form
class Author(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Comics(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=12, decimal_places=4, default=0)
    publish = models.DateField(default=timezone.now)

    def __str__(self):
        return self.title


# chained dropdown
class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class DogName(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=100)
    # birthdate = models.DateField(null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

templates/formset/add_bird.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add bird</title>
</head>
<body>
    <h1>Add a new bird</h1>
    <form id="form-container" method="POST">
        {% csrf_token %}
        {{bird_formset.management_form}}
        {% for form in form_formset %}
        <div class="bird-form">
        {{form.as_p}}
        </div>
        {% endfor %}
        <button id="add-form" type="button">Add Another Bird</button>
        <button type="submit">Create Birds</button>
    </form>


    <script>
        let birdForm = document.querySelectorAll(".bird-form")
        let container = document.querySelector("#form-container")
        let addButton = document.querySelector("#add-form")
        let totalForms = document.querySelector("#id_form-TOTAL_FORMS")

        let formNum = birdForm.length-1
        addButton.addEventListener('click', addForm)

        function addForm(e){
            e.preventDefault()

            let newForm = birdForm[0].cloneNode(true)
            let formRegex = RegExp(`form-(\\d){1}-`,'g')

            formNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
            container.insertBefore(newForm, addButton)

            totalForms.setAttribute('value', `${formNum+1}`)
        }
    </script>
    </body>
</html>

templates/formset/add_bird2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add bird</title>
</head>
<body>
<h1>Add a new bird</h1>
<form id="form-container" method="POST">
    {% csrf_token %}
    {{ bird_formset.management_form }}
    {% for form in bird_formset %}
        <div class="empty-form">
            {{ form.as_p }}
        </div>
    {% endfor %}
    <button id="data-formset-remove-form" type="button">Add Another Bird</button>
    <button type="submit">Create Birds</button>
</form>

<script>


    function Formset(element) {
        /*
          Dynamic Formset handler for Django formsets.

        Events:

          * init.formset
          * add-form.formset
          * remove-form.formset
          * renumber-form.formset

        */
        if (!(this instanceof Formset)) {
            return new Formset(element);
        }
        var formset = this;
        var emptyForm = element.querySelector('.empty-form').firstElementChild;
        var formsList = element.querySelector('.forms');

        var initialForms = element.querySelector('[name$=INITIAL_FORM_COUNT]');
        var totalForms = element.querySelector('[name$=TOTAL_FORM_COUNT]');
        var prefix = initialForms.name.replace(/INITIAL_FORM_COUNT$/, '');

        function addForm(event) {
            // Duplicate empty form.
            var newForm = emptyForm.cloneNode(true);
            // Update all references to __prefix__ in the elements names.
            renumberForm(newForm, '__prefix__', totalForms.value);
            // Make it able to delete itself.
            newForm.querySelector('[data-formset-remove-form]').addEventListener('click', removeForm);
            // Append the new form to the formsList.
            formsList.insertAdjacentElement('beforeend', newForm);
            element.dispatchEvent(new CustomEvent('add-form.formset', {
                detail: {
                    form: newForm,
                    formset: formset
                }
            }));
            // Update the totalForms.value
            totalForms.value = Number(totalForms.value) + 1;
        }

        function getForm(target) {
            var parent = target.parentElement;
            if (parent == document) {
                return null;
            }
            if (parent == formsList) {
                return target;
            }
            return getForm(parent);
        }

        function renumberForm(form, oldValue, newValue) {
            var matchValue = prefix + oldValue.toString()
            var match = new RegExp(matchValue);
            var replace = prefix + newValue.toString();

            ['name', 'id', 'for'].forEach(function (attr) {
                form.querySelectorAll('[' + attr + '*=' + matchValue + ']').forEach(function (el) {
                    el.setAttribute(attr, el.getAttribute(attr).replace(match, replace));
                });
            });

            element.dispatchEvent(new CustomEvent('renumber-form.formset', {
                detail: {
                    form: form,
                    oldValue: oldValue,
                    newValue: newValue,
                    formset: formset
                }
            }));
        }

        function removeForm(event) {
            // Find the form "row": the child of formsList that is the parent of the element
            // that triggered this event.
            var formToRemove = getForm(event.target);
            // Renumber the rows that come after us.
            var nextElement = formToRemove.nextElementSibling;
            var nextElementIndex = Array.prototype.indexOf.call(formsList.children, formToRemove);
            while (nextElement) {
                renumberForm(nextElement, nextElementIndex + 1, nextElementIndex);
                nextElement = nextElement.nextElementSibling;
                nextElementIndex = nextElementIndex + 1;
            }
            // Remove this row.
            formToRemove.remove();
            element.dispatchEvent(new CustomEvent('remove-form.formset', {
                detail: {
                    form: formToRemove,
                    formset: formset
                }
            }));
            // Decrement the management form's count.
            totalForms.value = Number(totalForms.value) - 1;
        }

        element.querySelector('[data-formset-add-form]').addEventListener('click', addForm);
        element.formset = this;

        element.dispatchEvent(new CustomEvent('init.formset', {
            detail: {
                formset: this
            }
        }));

        this.addForm = addForm;
    }

    new Formset(document.querySelector('#demo'));

</script>
</body>
</html>

templates/formset/add_bird3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add bird</title>
</head>
<body>
<h1>Add a new bird</h1>
<form id="form-horizontal" method="POST" action="">
    {% csrf_token %}
    {{ form_formset.management_form }}
    {% for form in form_formset %}
        <div class="row form-row spacer">
            <div class="col-2">
                <label>{{ form.name.label }}</label>
            </div>
            <div class="col-4">
                <div class="input-group">
                    {{ form.as_p }}
                    <div class="input-group-append">
                        <button class="btn btn-success add-form-row">Add Another Bird</button>
                    </div>
                </div>
            </div>

        </div>
    {% endfor %}
    <div class="row spacer">
        <div class="col-4 offset-2">
            <button class="btn btn-block btn-primary" type="submit">Create Birds</button>
        </div>
    </div>

</form>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>

<script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

<script>


    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+)');
        var replacement = prefix + '-' + ndx;
        if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
    }

    function cloneMore(selector, prefix) {
        var newElement = $(selector).clone(true);
        var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
        newElement.find(':input').each(function () {
            if ($(this).attr('name')) {
                var name = $(this).attr('name').replace('-' + (total - 1) + '-', '-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
            }
        });
        newElement.find('label').each(function () {
            var forValue = $(this).attr('for');
            if (forValue) {
                forValue = forValue.replace('-' + (total - 1) + '-', '-' + total + '-');
                $(this).attr({'for': forValue});
            }
        });
        total++;
        $('#id_' + prefix + '-TOTAL_FORMS').val(total);
        $(selector).after(newElement);
        var conditionRow = $('.form-row:not(:last)');
        conditionRow.find('.btn.add-form-row')
            .removeClass('btn-success').addClass('btn-danger')
            .removeClass('add-form-row').addClass('remove-form-row')
            .html('<span class="glyphicon glyphicon-minus" aria-hidden="true"></span>');
        return false;
    }

    function deleteForm(prefix, btn) {
        var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        if (total > 1) {
            btn.closest('.form-row').remove();
            var forms = $('.form-row');
            $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
            for (var i = 0, formCount = forms.length; i < formCount; i++) {
                $(forms.get(i)).find(':input').each(function () {
                    updateElementIndex(this, prefix, i);
                });
            }
        }
        return false;
    }

    $(document).on('click', '.add-form-row', function (e) {
        e.preventDefault();
        cloneMore('.form-row:last', 'form');
        return false;
    });
    $(document).on('click', '.remove-form-row', function (e) {
        e.preventDefault();
        deleteForm('form', $(this));
        return false;
    });

</script>
</body>
</html>

templates/formset/author_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>
<div class = "container">
	<h1>Author Form</h1>
	<form method = 'POST' action= '' enctype = "multipart/form-data" novalidate id = "author-form">{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value = "Submit" />
	</form>
</div>
</body>
</html>

templates/formset/bird_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bird List</title>
</head>
<body>
    <h1>Bird List</h1>
    <a href='{% url 'snippets:add_bird' %}'>Add bird</a>
    {% for bird in object_list %}
        <p>{{bird.common_name}}: {{bird.scientific_name}}</p>
    {% endfor %}
</body>
</html>

templates/formset/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book List</title>
</head>
<body>
{% for book in book_list %}
    <h4>{{ book.name }}</h4>


{% endfor %}

</body>
</html>

templates/formset/comics_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <h1>Create a Book</h1>
        <form method='POST' action='' enctype="multipart/form-data" novalidate id="book-form">{% csrf_token %}
            <label for="book-title" class="control-label">Book Title</label>
            {{ form.title }}
            <br><br>
            <label for="book-author" class="control-label">Book Author</label>
            {{ form.author }}
            <a href="/snippets/author/create" id="add_author" onclick="return showAddPopup(this);"><img
                    src="{% static '/images/icon-addlinks.png' %}"></a>
            <a id="edit_author" style="cursor: pointer;"><img
                    src="{% static '/images/icon-changelinks.svg' %}"></a>
            <br><br>
            <label for="book-price" class="control-label">Book Price</label>
            {{ form.price }}
            <br><br>
            <label for="book-publish" class="control-label">Book Publish</label>
            {{ form.publish }}
            <input type="submit" value="Submit"/>
        </form>
    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript">
        $("#edit_author").click(function () {
            author_name = $("#id_author option:selected").text();
            var data = {"author_name": author_name};
            $.ajax({
                type: 'GET',
                url: '/snippets/author/ajax/get_author_id/',
                data: data,
                success: function (data) {
                    var url = "/snippets/author/" + data['author_id'] + "/edit/";
                    showEditPopup(url);
                },
                error: function (data) {
                    alert("Something Went Wrong");
                }
            });
            return false;
        });
    </script>

    <script type="text/javascript">
        function showEditPopup(url) {
            var win = window.open(url, "Edit",
                'height=500,width=800,resizable=yes,scrollbars=yes');
            return false;
        }

        function showAddPopup(triggeringLink) {
            var name = triggeringLink.id.replace(/^add_/, '12345');
            href = triggeringLink.href;
            var win = window.open(href, name, 'height=500,width=800,resizable=yes,scrollbars=yes');
            win.focus();
            return false;
        }

        function closePopup(win, newID, newRepr, id) {
            $(id).append('<option value=' + newID + ' selected >' + newRepr + '</option>')
            win.close();
        }

    </script>
{% endblock %}

templates/formset/create_normal.html
<!-- create_normal.html :: part 3 -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

</head>
<title>
</title>

<body>
<form class="form-horizontal" method="POST" action="">
    {% csrf_token %}
    {{ formset.management_form }}
    {% for form in formset %}
        <div class="row form-row spacer">
            <div class="col-2">
                <label>{{ form.name.label }}</label>
            </div>
            <div class="col-4">
                <div class="input-group">
                    {{ form.name }}
                    <div class="input-group-append">
                        <button class="btn btn-success add-form-row">Add More</button>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    <div class="row spacer">
        <div class="col-4 offset-2">
            <button type="submit" class="btn btn-block btn-primary">Create</button>
        </div>
    </div>
</form>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>

<script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>


<!-- create_normal.html :: part 4 -->

<script type='text/javascript'>
    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+)');
        var replacement = prefix + '-' + ndx;
        if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
    }

    function cloneMore(selector, prefix) {
        var newElement = $(selector).clone(true);
        var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
        newElement.find(':input').each(function () {
            if ($(this).attr('name')) {
                var name = $(this).attr('name').replace('-' + (total - 1) + '-', '-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
            }
        });
        newElement.find('label').each(function () {
            var forValue = $(this).attr('for');
            if (forValue) {
                forValue = forValue.replace('-' + (total - 1) + '-', '-' + total + '-');
                $(this).attr({'for': forValue});
            }
        });
        total++;
        $('#id_' + prefix + '-TOTAL_FORMS').val(total);
        $(selector).after(newElement);
        var conditionRow = $('.form-row:not(:last)');
        conditionRow.find('.btn.add-form-row')
            .removeClass('btn-success').addClass('btn-danger')
            .removeClass('add-form-row').addClass('remove-form-row')
            .html('<span class="glyphicon glyphicon-minus" aria-hidden="true">Delete</span>');
        return false;
    }

    function deleteForm(prefix, btn) {
        var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        if (total > 1) {
            btn.closest('.form-row').remove();
            var forms = $('.form-row');
            $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
            for (var i = 0, formCount = forms.length; i < formCount; i++) {
                $(forms.get(i)).find(':input').each(function () {
                    updateElementIndex(this, prefix, i);
                });
            }
        }
        return false;
    }

    $(document).on('click', '.add-form-row', function (e) {
        e.preventDefault();
        cloneMore('.form-row:last', 'form');
        return false;
    });
    $(document).on('click', '.remove-form-row', function (e) {
        e.preventDefault();
        deleteForm('form', $(this));
        return false;
    });
</script>

</body>