snippets/urls.py
from django.urls import path, include
from snippets import views
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import url

app_name = 'snippets'

urlpatterns = [
    # path('snippets/', views.snippet_list),
    # path('snippets/', views.SnippetList.as_view(), name='snippet-list'),
    # # # path('snippets/<int:pk>/', views.snippet_detail),
    # path('snippets/<int:pk>/', views.SnippetDetail.as_view(), name='snippet-detail'),
    # path('users/', views.UserList.as_view(), name='user-list'),
    # path('users/<int:pk>/', views.UserDetail.as_view(), name='user-detail'),

    path('create_book_normal/', views.create_book_normal, name='create_book_normal'),
    path('book_list/', views.BookList.as_view(), name='book_list'),
    path('add_bird/', views.BirdAddView.as_view(), name="add_bird"),
    path('bird_list/', views.BirdListView.as_view(), name="bird_list"),

    path('person_list/', views.PersonListView.as_view(), name='person_changelist'),
    path('person_add/', views.PersonCreateView.as_view(), name='person_add'),
    path('person_change/<int:pk>/', views.PersonUpdateView.as_view(), name='person_change'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('ajax/load-models/', views.load_model_type, name='ajax_load_models'),
]

urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),
    path('', views.api_root),
    path('snippets/<int:pk>/highlight', views.SnippetHighlight.as_view(), name='snippet-highlight'),
]

urlpatterns += [
    # url(r'^book/create', views.ComicsCreate, name="BookCreate"),
    # url(r'^author/create', views.AuthorCreatePopup, name="AuthorCreate"),
    # url(r'^author/(?P<pk>\d+)/edit', views.AuthorEditPopup, name="AuthorEdit"),
    # url(r'^author/ajax/get_author_id', views.get_author_id, name="get_author_id"),
    path('comics/create/', views.ComicsCreate, name="ComicsCreate"),
    path('author/create/', views.AuthorCreatePopup, name="AuthorCreate"),
    path('author/<int:pk>/edit/', views.AuthorEditPopup, name="AuthorEdit"),
    path('author/ajax/get_author_id/', views.get_author_id, name="get_author_id"),
]
# urlpatterns = format_suffix_patterns(urlpatterns)

tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('snippets/', include('snippets.urls', namespace='snippets')),
    path('drawcircuit/', include('drawcircuit.urls', namespace='drawcircuit')),

]

snippets/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles

from pygments.lexers import get_lexer_by_name
from pygments.formatters.html import HtmlFormatter
from pygments import highlight

LEXERS = [item for item in get_all_lexers() if item[1]]
LANGUAGE_CHOICE = sorted([(item[1][0], item[0]) for item in LEXERS])
STYLE_CHOICES = sorted([(item, item) for item in get_all_styles()])


class Snippet(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100, blank=True, default='')
    code = models.TextField()
    linenos = models.BooleanField(default=False)
    language = models.CharField(choices=LANGUAGE_CHOICE, default='python', max_length=100)
    style = models.CharField(choices=STYLE_CHOICES, default='friendly', max_length=100)
    owner = models.ForeignKey('auth.User', related_name='snippets', on_delete=models.CASCADE)
    highlighted = models.TextField()

    class Meta:
        ordering = ['created']

    def save(self, *args, **kwargs):
        # use pygments lib to create highlighted HTML, representation of the code snippet
        lexer = get_lexer_by_name(self.language)
        linenos = 'table' if self.linenos else None
        options = {'title': self.title} if self.title else {}
        formatter = HtmlFormatter(style=self.style, linenos=linenos, full=True, **options)
        self.highlighted = highlight(self.code, lexer, formatter)
        super(Snippet, self).save(*args, **kwargs)


class Book(models.Model):
    name = models.CharField(max_length=255)
    isbn_number = models.CharField(max_length=13)

    class Meta:
        db_table = 'book'

    def __str__(self):
        return self.name


class Bird(models.Model):
    common_name = models.CharField(max_length=250)
    scientific_name = models.CharField(max_length=250)

    def __str__(self):
        return self.common_name


# Add/Edit button on Form
class Author(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Comics(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=12, decimal_places=4, default=0)
    publish = models.DateField(default=timezone.now)

    def __str__(self):
        return self.title


# chained dropdown
class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class DogName(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=100)
    # birthdate = models.DateField(null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

snippets/forms.py
from django import forms
from django.forms import formset_factory, ModelForm, modelformset_factory

from snippets.models import *


class BookForm(forms.Form):
    name = forms.CharField(
        label='Book Name',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter Book Name here'
        })
    )


BookFormset = formset_factory(BookForm, extra=1)

BirdFormSet = modelformset_factory(
    Bird, fields=("common_name", "scientific_name"), extra=1
)

from django.forms import ModelForm
from .models import Comics, Author


class ComicsForm(ModelForm):
    class Meta:
        model = Comics
        fields = [
            "title",
            "author",
            "price",
            "publish",
        ]


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = [
            "name"
        ]


class PersonForm(forms.ModelForm):
    model_choices = (
        ('country', 'Country'),
        ('city', 'City'),
        ('dogname', 'DogName')
    )

    test_model_field = forms.ChoiceField(choices=model_choices)
    test_instance_field = forms.ChoiceField(choices=[])
    # test_instance_field = forms.ModelChoiceField(queryset=DogName.objects.all())


    class Meta:
        model = Person
        fields = ('name', 'country', 'city')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
                self.fields['test_instance_field'].queryset = City.objects.all()
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

snippets/views/dropdown_list.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy

from snippets.forms import PersonForm
from snippets.models import *

from django.apps import apps


class PersonListView(ListView):
    model = Person
    context_object_name = 'people'
    template_name = 'dropdown_list/person_list.html'


class PersonCreateView(CreateView):
    model = Person
    form_class = PersonForm
    success_url = reverse_lazy('person_changelist')
    template_name = 'dropdown_list/person_create.html'


class PersonUpdateView(UpdateView):
    model = Person
    form_class = PersonForm
    success_url = reverse_lazy('person_changelist')
    template_name = 'dropdown_list/person_update.html'


def load_cities(request):
    country_id = request.GET.get('country')
    cities = City.objects.filter(country_id=country_id).order_by('name')
    return render(request, 'dropdown_list/city_dropdown_list_options.html', {'cities': cities})


def load_model_type(request):
    test_model_field_value = request.GET.get('test_model_field_value')
    print(test_model_field_value)
    model_name = apps.get_model('snippets', test_model_field_value)
    print(model_name)
    cities = model_name.objects.all()
    print(cities)
    return render(request, 'dropdown_list/city_dropdown_list_options.html', {'cities': cities})

templates/dropdown_list/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

templates/dropdown_list/person_create.html
{% extends 'base.html' %}

{% block content %}

  <h2>Person Form</h2>

{#  <form method="post" id="personForm" data-cities-url="{% url 'snippets:ajax_load_cities' %}" novalidate>#}
  <form method="post" id="personForm" data-cities-url="{% url 'snippets:ajax_load_models' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'snippets:person_changelist' %}">Nevermind</a>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
{#  <script>#}
{#    $("#id_country").change(function () {#}
{#      var url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view#}
{#      var countryId = $(this).val();  // get the selected country ID from the HTML input#}
{##}
{#      $.ajax({                       // initialize an AJAX request#}
{#        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)#}
{#        data: {#}
{#          'country': countryId       // add the country id to the GET parameters#}
{#        },#}
{#        success: function (data) {   // `data` is the return of the `load_cities` view function#}
{#          $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server#}
{#        }#}
{#      });#}
{##}
{#    });#}
{#  </script>#}


    <script>
    $("#id_test_model_field").change(function () {
      var url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
      var countryId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'test_model_field_value': countryId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_test_instance_field").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>

{% endblock %}

templates/dropdown_list/person_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/dropdown_list/person_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>